algoritmo "Repeticao2"
// Função :
// Autor :
// Data : 19/10/2021
// Seção de Declarações
var
   contador,salto, valor: inteiro
inicio
// Seção de Comandos
   contador<-0
   Escreva("Quer contar até que valor? ")
   leia(valor)
   Escreva("Qual será o valor do salto? ")
   leia(salto)
   Enquanto (contador<=valor) faca
            Escreval(contador)
            contador<-contador+salto
   FimEnquanto
   Escreval("Terminei de contar")
fimalgoritmo
