algoritmo "Comando de entrada e Operadores"
// Função : Solicitar dois números para o usuário mostrar a soma entre eles
// Autor :  Luana
// Data : 30/09/2021
// Seção de Declarações 
var
     n1, n2: inteiro
     m: real
inicio
// Seção de Comandos 
   Escreva("Digite um numero: ")
   leia(n1)
   Escreva("Digite outro numero: ")
   leia(n2)
    m<-(n1+n2)/2
   Escreva("A média dos valores de: ",n1," e",n2," é", m)
fimalgoritmo
